# Generated by Django 4.2.4 on 2024-01-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("PublicUsers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Filings_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de radicado",
                    ),
                ),
                (
                    "Filings_description",
                    models.CharField(max_length=50, verbose_name="Descripción"),
                ),
                ("Filings_receive_at_home", models.BooleanField(default=False)),
                ("Filings_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FilingsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FilingsType_code",
                    models.CharField(default="-", max_length=10, unique=True),
                ),
                ("FilingsType_description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FilingsUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FilingsUsers_filing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Filings.filings",
                    ),
                ),
                (
                    "FilingsUsers_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PublicUsers.publicusers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilingsAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FilingsAddress_address",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                (
                    "FilingsAddress_filing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Filings.filings",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="filings",
            name="Filings_td",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Filings.filingstype"
            ),
        ),
    ]
