# Generated by Django 4.2.4 on 2024-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Filings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filings",
            name="Filings_attached_file",
            field=models.FileField(
                blank=True, null=True, upload_to="Filings/attached_files/"
            ),
        ),
    ]
