# Generated by Django 5.1 on 2024-08-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_remove_publicusers_unique_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_code', models.CharField(max_length=10, unique=True)),
                ('rt_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_create_at', models.DateTimeField(auto_now_add=True)),
                ('r_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de radicado')),
                ('r_description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('r_receive_at_home', models.BooleanField(default=False)),
                ('r_attached_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivos Adjuntos')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.publicusers')),
                ('r_rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.recordtype')),
            ],
        ),
    ]
