# Generated by Django 5.1 on 2024-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicusers',
            name='unique_document',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='DocumentType_code',
            new_name='dt_code',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='DocumentType_description',
            new_name='dt_description',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_created_at',
            new_name='pu_created_at',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_dt',
            new_name='pu_dt',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_email',
            new_name='pu_email',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_name',
            new_name='pu_name',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_number',
            new_name='pu_number',
        ),
        migrations.RenameField(
            model_name='publicusers',
            old_name='public_user_phone',
            new_name='pu_phone',
        ),
        migrations.AddField(
            model_name='publicusers',
            name='pu_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddConstraint(
            model_name='publicusers',
            constraint=models.UniqueConstraint(fields=('pu_dt', 'pu_number'), name='unique_document_number'),
        ),
    ]
