# Generated by Django 4.2.4 on 2024-01-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DocumentType_code", models.CharField(max_length=10, unique=True)),
                ("DocumentType_description", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PublicUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_user_numberTd",
                    models.CharField(max_length=50, verbose_name="Número de documento"),
                ),
                (
                    "public_user_name",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "public_user_email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "public_user_phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telefono"
                    ),
                ),
                ("public_user_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "public_user_td",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PublicUsers.documenttype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="publicusers",
            constraint=models.UniqueConstraint(
                fields=("public_user_td", "public_user_numberTd"),
                name="unique_document",
            ),
        ),
    ]
